version: "3.8"

services:
  db:
    image: postgres:17.2
    container_name: myapp
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - myapp-network

volumes:
  db_data:

networks:
  myapp-network:
    driver: bridge