springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: alpha
  api-docs:
    path: /v3/api-docs
com:
  example:
   config:
     log-execution:
        enabled: true
     audit-execution:
      enabled: true
server:
  port: 8080
spring:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  datasource:
    driver-class-name: org.postgresql.Driver
    password: root
    username: root
    url: jdbc:postgresql://localhost:5432/myapp
  application:
    name: my-app
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
open.weather:
  sdk:
    key: 7e37c875a0722eb2f61a58b26135b98d


