com:
  example:
    config:
      log: true
      audit: true
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: alpha
  api-docs:
    path: /v3/api-docs
server:
  port: 8080
spring:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  datasource:
    driver-class-name: org.postgresql.Driver
    password: root
    username: root
    url: jdbc:postgresql://localhost:5432/myapp
  application:
    name: my-app
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        use_sql_comments: true
open.weather:
  sdk:
    key: 7e37c875a0722eb2f61a58b26135b98d
logging:
  level:
    org:
      springframework: info
      springdoc: info

